name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [test-clj, test-cljs]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Setup CI environment
      uses: yetanalytics/actions/setup-env@v0.0.4

    - name: Run Makefile Target ${{ matrix.target }}
      run: make ${{ matrix.target }}
